# just for building the ts app, we need ts, while running the build file, no need
FROM node:20-alpine3.19

WORKDIR /home/app

COPY package*.json .
COPY tsconfig.json .

RUN npm install

COPY src/ src/

RUN npm run build

CMD ["npm", "start"]